begin;
insert into statuses (status, description, abbreviation, color, closed, can_be_run, ignored)
values
('PRIORITY', 'High priority', 'PRIORITY', 'red', false, true, false),
('CLOSED', 'Closed', 'CLOSED', 'green', true, false, false),
('FREEZED', 'Freezed', 'FREEZED', 'blue', true, false, false), 
('NOTE', 'Note', 'NOTE', 'transparent', false, true, true),
('INVOICE', 'Waiting for invoice', 'INVOICE', 'seagreen', true, false, false),
('INVOICED', 'Invoiced', 'INVOICED', 'lightgreen', true, false, false),
('NEW', 'Open', 'NEW', 'transparent', false, true, false),
('ARCHIVE', 'Archived', 'ARCHIVE', 'transparent', false, false, false);

insert into status_order (previous_status, next_status)
values
(null, 'NEW'),
('INVOICED', 'CLOSED'),
('INVOICED', 'ARCHIVE'),
('CLOSED', 'INVOICED'),
('CLOSED', 'ARCHIVE'),
(null, 'NOTE'),
(null, 'PRIORITY'),
('NOTE', 'NOTE'),
('NOTE', 'PRIORITY'),
('NOTE', 'INVOICED'),
('NOTE', 'CLOSED'),
('NOTE', 'ARCHIVE'),
('PRIORITY', 'ARCHIVE'),
('PRIORITY', 'NOTE'),
('PRIORITY', 'INVOICED'),
('PRIORITY', 'CLOSED'),
(null, 'FREEZED'),
('PRIORITY', 'FREEZED'),
('NOTE', 'FREEZED'),
('PRIORITY', 'INVOICE'),
('NOTE', 'INVOICE'),
('CLOSED', 'INVOICE'),
('FREEZED', 'INVOICE'),
('INVOICE', 'INVOICED'),
('INVOICE', 'CLOSED'),
('INVOICE', 'ARCHIVE'),
('FREEZED', 'NOTE'),
('FREEZED', 'PRIORITY'),
('FREEZED', 'ARCHIVE'),
('FREEZED', 'CLOSED'),
('FREEZED', 'INVOICED'),
('FREEZED', 'NEW'),
('NOTE', 'NEW'),
('CLOSED', 'NEW'),
('PRIORITY', 'NEW'),
('INVOICE', 'NEW'),
('NEW', 'CLOSED'),
('NEW', 'FREEZED'),
('NEW', 'INVOICE'),
('NEW', 'NOTE'),
('NEW', 'PRIORITY');
commit;
